version: '3.9'

services:
  migrate:
    image: migrate/migrate
    networks:
      - Time
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", 
              "postgres://postgres:feruza1727@postgres:5432/timecapsule?sslmode=disable",
              "up" ]
    # depends_on:

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - Time
  
  auth-service:
    container_name: auth
    build: .
    # depends_on:
    #   - kafka /////////////////////////////////////////////

    ports:
      - "8090:8090"
      - "8088:8088"
    networks:
      - Time
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=feruza1727
      - DB_NAME=timecapsule
      - KAFKA_BROKER=kafka:9092

networks:
  Time:
    external: true
    name: Time
    driver: bridge

volumes:
  db:
